Search.appendIndex(
    [
                {
            "fqsen": "\\showInstruments\u0028\u0029",
            "name": "showInstruments",
            "summary": "Get\u0020available\u0020instruments\u0020\u0028completed,\u0020partially\u0020completed,\u0020not\u0020completed\u0029",
            "url": "namespaces/default.html#function_showInstruments"
        },                {
            "fqsen": "\\curl_redcap_api\u0028\u0029",
            "name": "curl_redcap_api",
            "summary": "Open\u0020curl\u0020redcap\u0020api",
            "url": "namespaces/default.html#function_curl_redcap_api"
        },                {
            "fqsen": "\\id_translation\u0028\u0029",
            "name": "id_translation",
            "summary": "ID\u0020translation",
            "url": "namespaces/default.html#function_id_translation"
        },                {
            "fqsen": "\\econsent\u0028\u0029",
            "name": "econsent",
            "summary": "Show\u0020consent\u0020form",
            "url": "namespaces/default.html#function_econsent"
        },                {
            "fqsen": "\\consent\u0028\u0029",
            "name": "consent",
            "summary": "Check\u0020if\u0020user\u0020consented",
            "url": "namespaces/default.html#function_consent"
        },                {
            "fqsen": "\\red_cap_api_inscription_metasante\u0028\u0029",
            "name": "red_cap_api_inscription_metasante",
            "summary": "Send\u0020registration\u0020data\u0020to\u0020M\u00E9tasant\u00E9\u0020\u0028REDCap\u0029",
            "url": "namespaces/default.html#function_red_cap_api_inscription_metasante"
        },                {
            "fqsen": "\\red_cap_api_inscription\u0028\u0029",
            "name": "red_cap_api_inscription",
            "summary": "Send\u0020registration\u0020data\u0020to\u0020M\u00E9tasant\u00E9\u0020\u002D\u0020Inscription\u0020\u0028REDCap\u0029",
            "url": "namespaces/default.html#function_red_cap_api_inscription"
        },                {
            "fqsen": "\\getInstrumentLabels\u0028\u0029",
            "name": "getInstrumentLabels",
            "summary": "Get\u0020instruments\u0027\u0020labels",
            "url": "namespaces/default.html#function_getInstrumentLabels"
        },                {
            "fqsen": "\\getInstrumentList\u0028\u0029",
            "name": "getInstrumentList",
            "summary": "Get\u0020instruments\u0020list",
            "url": "namespaces/default.html#function_getInstrumentList"
        },                {
            "fqsen": "\\getSurveyLink\u0028\u0029",
            "name": "getSurveyLink",
            "summary": "Get\u0020survey\u0020link",
            "url": "namespaces/default.html#function_getSurveyLink"
        },                {
            "fqsen": "\\survey_complete\u0028\u0029",
            "name": "survey_complete",
            "summary": "Get\u0020survey\u0020fields\u0020\u0028completed,\u0020partially\u0020completed,\u0020not\u0020completed\u0029",
            "url": "namespaces/default.html#function_survey_complete"
        },                {
            "fqsen": "\\getAvailableInstruments\u0028\u0029",
            "name": "getAvailableInstruments",
            "summary": "Get\u0020available\u0020instruments\u0020\u0028completed,\u0020partially\u0020completed,\u0020not\u0020completed\u0029",
            "url": "namespaces/default.html#function_getAvailableInstruments"
        },                {
            "fqsen": "\\completion_percent\u0028\u0029",
            "name": "completion_percent",
            "summary": "Get\u0020percent\u0020of\u0020instrument\u0020completion",
            "url": "namespaces/default.html#function_completion_percent"
        },                {
            "fqsen": "\\print_r2\u0028\u0029",
            "name": "print_r2",
            "summary": "",
            "url": "namespaces/default.html#function_print_r2"
        },                {
            "fqsen": "\\is_completed\u0028\u0029",
            "name": "is_completed",
            "summary": "Is\u0020the\u0020instrument\u0020completed\u003F",
            "url": "namespaces/default.html#function_is_completed"
        },                {
            "fqsen": "\\left_join_array\u0028\u0029",
            "name": "left_join_array",
            "summary": "PHP\u0020left\u0020join",
            "url": "namespaces/default.html#function_left_join_array"
        },                {
            "fqsen": "\\getArm\u0028\u0029",
            "name": "getArm",
            "summary": "Get\u0020arm",
            "url": "namespaces/default.html#function_getArm"
        },                {
            "fqsen": "\\address_is_valid\u0028\u0029",
            "name": "address_is_valid",
            "summary": "Address\u0020validation",
            "url": "namespaces/default.html#function_address_is_valid"
        },                {
            "fqsen": "\\delete_in_redcap\u0028\u0029",
            "name": "delete_in_redcap",
            "summary": "",
            "url": "namespaces/default.html#function_delete_in_redcap"
        },                {
            "fqsen": "\\modify_in_redcap\u0028\u0029",
            "name": "modify_in_redcap",
            "summary": "",
            "url": "namespaces/default.html#function_modify_in_redcap"
        },                {
            "fqsen": "\\",
            "name": "\\",
            "summary": "",
            "url": "namespaces/default.html"
        }            ]
);
